/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Certificate content for Blum account verification with Telegram-based user verification including sybil and activity scores.
 */
export interface BlumCertificateContent {
  /**
   * The Telegram user ID.
   */
  telegramId: string;
  /**
   * User activity metric.
   */
  activityScore: number;
  /**
   * Sybil resistance score.
   */
  sybilScore: number;
}
